version: '3.8'
services:
    server:
        build:
            context: .
            dockerfile: ./server/Dockerfile
        ports:
            - '4000:4000'
    src:
        build:
            context: .
            dockerfile: ./src/Dockerfile
        ports:
            - '5000:5000'
        depends_on:
            - server

    postgres:
        container_name: postgres
        image: postgres:11.5
        env_file:
            - .env
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        restart: unless-stopped
