version: '3.3'
services:
    server:
        build:
            context: .
            dockerfile: ./server/Dockerfile
        ports:
            - '4000:4000'
        command: npm run start:dev
    # src:
    #     build:
    #         context: .
    #         dockerfile: ./src/Dockerfile
    #     ports:
    #         - '5000:5000'
    #     depends_on:
    #         - server
    #     command: npm run start

    postgres:
        container_name: postgres
        image: postgres:11.5
        env_file:
            - .env
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        restart: unless-stopped
